### ISSUE TITLE
Добавь лицензию

### ISSUE THREAD

**Issue by GuvaCode** [turborium/TurboRaylib#1]
Если хочешь добавить в список биндингов то добавь лицензию иначе Санта марина к этому придередся.

**Comment by turborium** [comment]
Есть же в корне LICENSE

**Comment by GuvaCode** [comment]
Опа. Сорян. Я чё-то мельком глянул и не увидел.

**Comment by turborium** [comment]
Рекомендую кста глянуть на этот баг - https://github.com/GuvaCode/Ray4Laz/issues/11 - это баг, из-за того что raylib меняет переданные структуры(а они передаются по факту через указатели, если не влезают в регистры), чего не ожидает Delphi/Pascal, чиниться "оборачиванием" функции. Впрочем меня выбесили приколы с cdecl (что для dll undefined)- я все обернул, от греха подальше.

**Comment by turborium** [comment]
да и вообще - передача/возврат(!!!) структур из/в dll/so - это сплошное undefined, когда начинал клепать биндинги, не заметил, в процессе - офигел.

**Comment by GuvaCode** [comment]
Да я посмотрел. Думаю тоже надо обернуть.
